---
defaults:
  install_options: --source http://gems.rubyforge.org --source http://gems.github.com --no-ri --no-rdoc
gems:
- name: rdoc
  version: >= 2.4.3
- name: rake
  version: ~> 0.8.4
- name: rails
  version: 2.3.4
- name: amatch
  version: 0.2.3
- name: cucumber
  version: 0.4.0
- name: fastercsv
  version: 1.4.0
- name: haml
  version: 2.0.9
- name: highline
  version: 1.5.0
- name: hpricot
  version: 0.6.164
- name: nokogiri
  version: 1.3.1
- name: mysql
  version: ~> 2.8.0
- name: rspec
  version: 1.2.8
- name: rspec-rails
  version: 1.2.7.1
- name: hoe
  version: 1.11.0
- name: chronic
  version: ~> 0.2.3
- name: whenever
  version: 0.4.0
- name: vlad
  version: ~> 1.3.2
- name: authlogic
  version: 2.1.1
- name: geokit
  version: 1.4.1
- name: webrat
  version: 0.5.3
- name: spork
  version: 0.5.11
