---
defaults:
  install_options: --include-dependencies
gems:
- name: actionmailer
  version: 2.2.2
- name: actionpack
  version: 2.2.2
- name: activerecord
  version: 2.2.2
- name: activeresource
  version: 2.2.2
- name: activesupport
  version: 2.2.2
- name: cucumber
  version: 0.2.0
- name: fastercsv
  version: 1.4.0
- name: haml
  version: 2.0.9
- name: highline
  version: 1.5.0
- name: hpricot
  version: 0.6.164
- name: mysql
  version: ~> 2.7
- name: rails
  version: 2.2.2
- name: rake
  version: 0.8.4
- name: rspec
  version: 1.1.12
- name: rspec-rails
  version: 1.1.12
- name: hoe
  version: 1.11.0
